### ISSUE TITLE
Command line transforms

### ISSUE THREAD

**Issue by aristidesfl** [BigstickCarpet/simplifyify#5]
Is it possible to use transforms in the command line with `-t coffeeify` without having to specify them in `package.json`?

**Comment by BigstickCarpet** [comment]
Not currently.  One of my main goals with Simplifiyify was to have as few command-line args as possible, to keep things simple.  As soon as you start specifying plugins and transforms on the CLI, things get much more complicated, and you're probably better-off just using Browserify directly instead of Simplifyify
